name: te_leo
description: "Una herramienta de lectura accesible para jóvenes con problemas de vista y dislexia"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.9.2


dependencies:
  flutter:
    sdk: flutter
  
  # Gestión de estado, navegación y dependencias
  get: ^4.6.6

  # Base de datos local
  sqflite: ^2.3.2
  path_provider: ^2.1.2
  path: ^1.8.3

  # Lógica de OCR y TTS
  google_mlkit_text_recognition: ^0.15.0  # Actualizado para compatibilidad con Android SDK 36
  flutter_tts: ^4.2.3  # Versión más reciente
  
  # Acceso a cámara y galería
  image_picker: ^1.0.7
  
  # Para temas y fuentes
  google_fonts: ^6.2.1
  
  # Actualizaciones de app y conectividad
  in_app_update: ^4.2.3
  package_info_plus: 4.2.0  # Versión fija con soporte Java
  url_launcher: ^6.2.5
  http: ^1.2.1
  
  # Persistencia de datos
  get_storage: ^2.1.1  # Almacenamiento rápido y moderno (reemplaza shared_preferences)
  
  # Notificaciones locales
  flutter_local_notifications: ^19.4.2  # Actualizado
  
  # Sistema Premium y Monetización
  in_app_purchase: ^3.1.11        # Compras in-app (Google Play + App Store)
  google_mobile_ads: ^6.0.0       # Anuncios de Google AdMob - Actualizado
  
  # Internacionalización
  flutter_localizations:
    sdk: flutter
  intl: any

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # Assets de la aplicación
  assets:
    - assets/
    - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
